```mermaid
erDiagram
    NOTIFICATION_TEMPLATES {
        int template_id PK
        string template_code
        string channel "EMAIL, IN_APP"
        string body_template
        string event_trigger
    }
    NOTIFICATIONS {
        uuid notification_id PK
        uuid user_id REF
        int template_id FK
        string recipient_email
        string title
        boolean is_read
    }
    
    NOTIFICATION_TEMPLATES ||--o{ NOTIFICATIONS : "uses"
```
